services:
  api:
    image: php:8.2-fpm
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./dpet-laravel-api:/var/www
    environment:
      - APP_ENV=local
    networks:
      - laravel_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./dpet-laravel-api:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    networks:
      - laravel_network

  app:
    image: node:18
    container_name: vue_app
    working_dir: /app
    volumes:
      - ./dpet-web-app:/app
    ports:
      - "8080:8080"
    command: sh -c "npm install && npm run serve"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
